// <auto-generated />
using System;
using Instrument.Defaults.Provider.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Instrument.Defaults.Provider.Sqlite.Migrations
{
    [DbContext(typeof(DefaultsDbContext))]
    [Migration("20250321023512_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Instrument.Defaults.Models.Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sequence");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 3, 21, 2, 35, 12, 42, DateTimeKind.Utc).AddTicks(7106),
                            Description = "Stop Station Home",
                            IsActive = true,
                            Name = "SS_Home"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 3, 21, 2, 35, 12, 42, DateTimeKind.Utc).AddTicks(7108),
                            Description = "Reaction Wheel Home",
                            IsActive = true,
                            Name = "ERW_Home"
                        });
                });

            modelBuilder.Entity("Instrument.Defaults.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Technology");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ImmunoCap"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ImmunoCapViewAllergy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "EliaDualWash"
                        });
                });

            modelBuilder.Entity("Instrument.Defaults.Models.TestMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "sIgE",
                            TechnologyId = 1
                        });
                });

            modelBuilder.Entity("Instrument.Defaults.Models.TestMethodSequences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestMethodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestMethodSequences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            SequenceId = 1,
                            TestMethodId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            SequenceId = 2,
                            TestMethodId = 1
                        });
                });

            modelBuilder.Entity("Instrument.Defaults.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "mm",
                            Description = "Millimeter",
                            Name = "Millimeter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
